"""alert_events: make threshold_pct nullable

Revision ID: a06a314c8940
Revises: bc646abdda09
Create Date: 2026-06-14 19:12:23.703138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a06a314c8940'
down_revision: Union[str, None] = 'bc646abdda09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_events', 'threshold_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_events', 'threshold_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    # ### end Alembic commands ###
